global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pki-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["pki-exporter.cert-lab.local:9091"]
